# Generated by Django 6.0.7 on 2026-07-09 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(max_length=255)),
                ('sla_days', models.IntegerField()),
                ('sla_type', models.CharField(choices=[('Business Day', 'Business Day'), ('Calendar Day', 'Calendar Day')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('finished', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_date', 'task_name'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(max_length=255)),
                ('sla_days', models.IntegerField()),
                ('sla_type', models.CharField(choices=[('Business Day', 'Business Day'), ('Calendar Day', 'Calendar Day')], max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'task_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=50)),
                ('changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.task')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
