# Generated by Django 6.0.7 on 2026-07-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sla_type',
            field=models.CharField(choices=[('Working Day', 'Working Day'), ('Calendar Day', 'Calendar Day')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='sla_type',
            field=models.CharField(choices=[('Working Day', 'Working Day'), ('Calendar Day', 'Calendar Day')], max_length=20),
        ),
    ]
