# Generated by Django 6.0.7 on 2026-07-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_group_task_group_tasktemplate_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
